In [ ]:
import numpy as np

r3,c3=map(int,input('Enter the size of batch in rows and columns : ').split())
x=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    x[i][j]=input('Enter: ')
print(x)

n=int(input('Enter the number of w matrix taken: '))
for p in range(1,n+1):

  def relu(a):
    return np.maximum(0,a)


  r1,c1=map(int,input('Enter the size of {0} w matrix : '.format(p)).split())
  r2=r1
  c2=1

  print('Elements of {0} w matrix: '.format(p))
  w=np.zeros((r1,c1))
  for i in range(r1):
    for j in range(c1):
      w[i][j]=input('Enter: ')
  print(w)

  print('Elements of {0} b matrix: '.format(p))
  b=np.zeros((r2,c2))
  for i in range(r2):
    for j in range(c2):
      b[i][j]=input('Enter: ')
  print(b)

  if p==1:
    z=np.dot(w,x)
    y=z+b
    print('Result: ')
    print(y)
    print('ReLU result: ')
    re_val=relu(y)
    print(re_val)
  else:
    z=np.dot(w,re_val)
    y=z+b
    print('Result: ')
    print(y)
    print('ReLU result: ')
    re_val=relu(y)
    print(re_val)






Enter the size of batch in rows and columns : 5 1
Enter: 2
Enter: 1
Enter: 3
Enter: 0
Enter: -1
[[ 2.]
 [ 1.]
 [ 3.]
 [ 0.]
 [-1.]]
Enter the number of w matrix taken: 4
Enter the size of 1 w matrix : 4 5
Elements of 1 w matrix: 
Enter: 1
Enter: 0
Enter: 0
Enter: 0
Enter: -1
Enter: 0
Enter: 1
Enter: 1
Enter: 0
Enter: 0
Enter: 0
Enter: 0
Enter: 1
Enter: 1
Enter: 1
Enter: 0
Enter: 0
Enter: 0
Enter: 0
Enter: 2
[[ 1.  0.  0.  0. -1.]
 [ 0.  1.  1.  0.  0.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  2.]]
Elements of 1 b matrix: 
Enter: 0
Enter: 0
Enter: 0
Enter: 1
[[0.]
 [0.]
 [0.]
 [1.]]
Result: 
[[ 3.]
 [ 4.]
 [ 2.]
 [-1.]]
ReLU result: 
[[3.]
 [4.]
 [2.]
 [0.]]
Enter the size of 2 w matrix : 3 4
Elements of 2 w matrix: 
Enter: 1
Enter: 0
Enter: 0
Enter: -1
Enter: 0
Enter: 1
Enter: -1
Enter: 0
Enter: 1
Enter: 0
Enter: 0
Enter: 0
[[ 1.  0.  0. -1.]
 [ 0.  1. -1.  0.]
 [ 1.  0.  0.  0.]]
Elements of 2 b matrix: 
Enter: 0
Enter: 0
Enter: -2
[[ 0.]
 [ 0.]
 [-2.]]
Result: 
[[3.]
 [2.]
 [1.]]
Re

In [ ]:
import numpy as np

def relu(a):
    return np.maximum(0,a)

r1,c1=map(int,input('Enter then number of rows and columns of w matrix: ').split())
print('Enter the elements of matrix: ')
w1=np.zeros((r1,c1))
for i in range(r1):
  for j in range(c1):
    w1[i][j]=input('Enter: ')
print(w1)

r3=r1
c3=1
print('Enter the elements of matrix: ')
b1=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    b1[i][j]=input('Enter: ')
print(b1)

r2,c2=map(int,input('Enter then number of rows and columns of batches: ').split())
print('Enter the elements of batch: ')
x1=np.zeros((r2,c2))
for i in range(r2):
  for j in range(c2):
    x1[i][j]=input('Enter: ')
print(x1)

z1=np.dot(w1,x1)
h1=z1+b1

print('result: ')
print(h1)
print('ReLU result: ')
re_val=relu(h1)
print(re_val)


r4,c4=map(int,input('Enter then number of rows and columns of Hidden Layer w matrix: ').split())
print('Enter the elements of matrix: ')
w2=np.zeros((r4,c4))
for i in range(r4):
  for j in range(c4):
    w2[i][j]=input('Enter: ')
print(w2)

r5=r4
c=1
print('Enter the elements of matrix: ')
b2=np.zeros((r5,c5))
for i in range(r5):
  for j in range(c5):
    b2[i][j]=input('Enter: ')
print(b2)

z2=np.dot(w2,re_val)
h2=z2+b2

print('result: ')
print(h2)
print('ReLU result: ')
re_val=relu(h2)
print(re_val)

Enter then number of rows and columns of w matrix: 1 1
Enter the elements of matrix: 
Enter: 2
[[2.]]
Enter the elements of matrix: 
Enter: 0
[[0.]]
Enter then number of rows and columns of batches: 1 1
Enter the elements of batch: 
Enter: 3
[[3.]]
result: 
[[6.]]
ReLU result: 
[[6.]]
Enter then number of rows and columns of Hidden Layer w matrix: 1 1
Enter the elements of matrix: 
Enter: 2
[[2.]]
Enter the elements of matrix: 
Enter: -1
[[-1.]]
result: 
[[11.]]
ReLU result: 
[[11.]]


In [ ]:
import numpy as np

r3,c3=map(int,input('Enter the size of batch in rows and columns : ').split())
x=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    x[i][j]=input('Enter: ')
print(x)


r1,c1=map(int,input('Enter the size of w matrix : ').split())
r2=r1
c2=1

print('Elements of w matrix: '.format(p))
w=np.zeros((r1,c1))
for i in range(r1):
  for j in range(c1):
    w[i][j]=input('Enter: ')
print(w)

print('Elements of b matrix: ')
b=np.zeros((r2,c2))
for i in range(r2):
  for j in range(c2):
    b[i][j]=input('Enter: ')
print(b)

z=np.dot(w,x)
y=z+b
print('\nResult :\n {0})'.format(y))





Enter the size of batch in rows and columns : 2 1
Enter: 2
Enter: 1
[[2.]
 [1.]]
Enter the size of 4 w matrix : 3 2
Elements of 4 w matrix: 
Enter: 1
Enter: 1
Enter: 1
Enter: -1
Enter: -1
Enter: 0
[[ 1.  1.]
 [ 1. -1.]
 [-1.  0.]]
Elements of 4 b matrix: 
Enter: 0
Enter: 1
Enter: 3
[[0.]
 [1.]
 [3.]]

Result :
 [[3.]
 [2.]
 [1.]])
