In [7]:
import numpy as np

r1,c1=map(int,input('Enter then number of rows and columns of 1 matrix : ').split())
print('Enter the elements of matrix 1 : ')
a=np.zeros((r1,c1))
for i in range(r1):
  for j in range(c1):
    a[i][j]=input('Enter: ')
print(a)

r2,c2=map(int,input('Enter then number of rows and columns of 2 matrix : ').split())
print('Enter the elements of matrix 2 : ')
b=np.zeros((r2,c2))
for i in range(r2):
  for j in range(c2):
    b[i][j]=input('Enter: ')
print(b)

if c1!=r2:
  print('Matrix Multiplication is not possible')

else:
  m=np.zeros((r1,c2))
  for i in range(r2):
    for j in range(c2):
      for k in range(c1):
        m[i][j]=m[i][j]+a[i][k]*b[k][j]
  print('Matrix Multiplication :\n{0}'.format(m))



Enter then number of rows and columns of 1 matrix : 5 4
Enter the elements of matrix 1 : 
Enter: 1
Enter: 1
Enter: 1
Enter: 0
Enter: 0
Enter: 1
Enter: 1
Enter: 1
Enter: 1
Enter: 0
Enter: 1
Enter: 1
Enter: 1
Enter: 1
Enter: 0
Enter: 1
Enter: 1
Enter: 1
Enter: -1
Enter: 1
[[ 1.  1.  1.  0.]
 [ 0.  1.  1.  1.]
 [ 1.  0.  1.  1.]
 [ 1.  1.  0.  1.]
 [ 1.  1. -1.  1.]]
Enter then number of rows and columns of 2 matrix : 4 5
Enter the elements of matrix 2 : 
Enter: 0
Enter: 0
Enter: 0
Enter: 1
Enter: 1
Enter: 1
Enter: 0
Enter: 1
Enter: 0
Enter: 1
Enter: 0
Enter: 1
Enter: 1
Enter: 0
Enter: 1
Enter: 0
Enter: 0
Enter: 0
Enter: 1
Enter: 0
[[0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 1.]
 [0. 0. 0. 1. 0.]]
Matrix Multiplication :
[[1. 1. 2. 1. 3.]
 [1. 1. 2. 1. 2.]
 [0. 1. 1. 2. 2.]
 [1. 0. 1. 2. 2.]
 [0. 0. 0. 0. 0.]]
