In [2]:
import numpy as np

r1,c1=map(int,input('Enter then number of rows and columns of w matrix: ').split())
print('Enter the elements of matrix: ')
w=np.zeros((r1,c1))
for i in range(r1):
  for j in range(c1):
    w[i][j]=input('Enter: ')
print(w)

r2=r1
c2=1
print('Enter the elements of bias matrix: ')
b=np.zeros((r2,c2))
for i in range(r2):
  for j in range(c2):
    b[i][j]=input('Enter: ')
print(b)

r3,c3=map(int,input('Enter then number of rows and columns of batches: ').split())
print('Enter the elements of batch: ')
x1=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    x1[i][j]=input('Enter: ')
print(x1)
z1=np.dot(w,x1)
y1=z1+b
print('Result : \n {0}'.format(y1))

Enter then number of rows and columns of w matrix: 3 3
Enter the elements of matrix: 
Enter: 1
Enter: 1
Enter: 0
Enter: 1
Enter: 1
Enter: 0
Enter: 1
Enter: 1
Enter: 0
[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]
Enter the elements of bias matrix: 
Enter: 0
Enter: -2
Enter: -4
[[ 0.]
 [-2.]
 [-4.]]
Enter then number of rows and columns of batches: 3 1
Enter the elements of batch: 
Enter: 2
Enter: 5
Enter: 1
[[2.]
 [5.]
 [1.]]
Result : 
 [[7.]
 [5.]
 [3.]]
