In [6]:
import numpy as np

r1,c1=map(int,input('Enter then number of rows and columns of w matrix: ').split())
print('Enter the elements of matrix: ')
w1=np.zeros((r1,c1))
for i in range(r1):
  for j in range(c1):
    w1[i][j]=input('Enter: ')
print(w1)
r3=r1
c3=1
print('Enter the elements of bias matrix: ')
b1=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    b1[i][j]=input('Enter: ')
print(b1)
r2,c2=map(int,input('Enter then number of rows and columns of batches: ').split())
print('Enter the elements of batch: ')
x1=np.zeros((r2,c2))
for i in range(r2):
  for j in range(c2):
    x1[i][j]=input('Enter: ')
print(x1)
h1=np.dot(w1,x1)+b1
print('result: ')
print(h1)

ch=int(input('Select the Operation :\n1.ReLU Function\n2.Sigmoid Function(3-Bit)\n3.Sigmoid Function(5-Bit)\n4.Tanh Function(3-Bit)\n5.Tanh Function(5-Bit)\n'))

if ch==1:
  def relu(a):
    return np.maximum(0,a)
  print('ReLU result: ')
  re_val=relu(h1)

elif ch==2:
  def sig(x):
    for i in range(0,len(x)):
      if x[i]<=-2:
        print('0')
      elif x[i]>=2:
        print('1')
      else:
        print('0.5')
    print('Sigmoid result: ')
    sig(h1)
elif ch==3:
  def sig(x):
    for i in range(0,len(x)):
      if x[i]<=-2:
        print('0')
      elif x[i]==-1:
        print('0.3')
      elif x[i]==0:
        print('0.5')
      elif x[i]==1:
        print('0.7')
      else:
        print('1')
    print('Sigmoid result: ')
    sig(h1)

elif ch==4:
  def tanh_f(x):
    for i in range(0,len(x)):
      if x[i]<=-2:
        print('-1')
      elif x[i]>=2:
        print('1')
      else:
        print('0')
    print('TanH result: ')
    tanh_f(h1)
elif ch==5:
  def tanh_f(x):
    for i in range(0,3):
      if x[i]<=-2:
        print('-1')
      elif x[i]==-1:
        print('-0.8')
      elif x[i]==0:
        print('0')
      elif x[i]==1:
        print('0.8')
      else:
        print('1')
  print('TanH result: ')
  tanh_f(h1)
else:
  print('Invalid Choice.')







Enter then number of rows and columns of w matrix: 3 2
Enter the elements of matrix: 
Enter: 1
Enter: -1
Enter: 1
Enter: -2
Enter: 1
Enter: -3
[[ 1. -1.]
 [ 1. -2.]
 [ 1. -3.]]
Enter the elements of bias matrix: 
Enter: 0
Enter: 0
Enter: 0
[[0.]
 [0.]
 [0.]]
Enter then number of rows and columns of batches: 2 1
Enter the elements of batch: 
Enter: 3
Enter: 2
[[3.]
 [2.]]
result: 
[[ 1.]
 [-1.]
 [-3.]]
ReLU result: 
[[1.]
 [0.]
 [0.]]
Sigmoid result: 
0.7
0.3
0
None
TanH result: 
0.8
-0.8
-1
None
