In [ ]:
import numpy as np
r1,c1=map(int,input('Enter then number of rows and columns of w matrix: ').split())
print('Enter the elements of matrix: ')
w=np.zeros((r1,c1))
for i in range(r1):
  for j in range(c1):
    w[i][j]=input('Enter: ')
print(w)
r3=r1
c3=1
print('Enter the elements of matrix: ')
b=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    b[i][j]=input('Enter: ')
print(b)
n=int(input('Enter number of batches: '))
r2,c2=map(int,input('Enter then number of rows and columns of batches: ').split())
p=1
for p in range(1,n+1):
  def relu(a):
    return np.maximum(0,a)
  print('Enter the elements of {0} batch: '.format(p))
  x1=np.zeros((r2,c2))
  for i in range(r2):
    for j in range(c2):
      x1[i][j]=input('Enter: ')
  print(x1)
  z1=np.dot(w,x1)
  y1=z1+b
  print('result: ')
  print(y1)
  print('ReLU result: ')
  re_val=relu(y1)
  print(re_val)

Enter then number of rows and columns of w matrix: 3 2
Enter the elements of matrix: 
Enter: 1
Enter: 0
Enter: 1
Enter: -1
Enter: 0
Enter: 1
[[ 1.  0.]
 [ 1. -1.]
 [ 0.  1.]]
Enter the elements of matrix: 
Enter: 1
Enter: 0
Enter: -1
[[ 1.]
 [ 0.]
 [-1.]]
Enter number of batches: 2
Enter then number of rows and columns of batches: 2 1
Enter the elements of 1 batch: 
Enter: 3
Enter: 2
[[3.]
 [2.]]
result: 
[[4.]
 [1.]
 [1.]]
ReLU result: 
[[4.]
 [1.]
 [1.]]
Enter the elements of 2 batch: 
Enter: -3
Enter: 2
[[-3.]
 [ 2.]]
result: 
[[-2.]
 [-5.]
 [ 1.]]
ReLU result: 
[[0.]
 [0.]
 [1.]]
