In [1]:
import numpy as np
def relu(a):
    return np.maximum(0,a)
r1,c1=map(int,input('Enter then number of rows and columns of w matrix: ').split())
print('Enter the elements of matrix: ')
w1=np.zeros((r1,c1))
for i in range(r1):
  for j in range(c1):
    w1[i][j]=input('Enter: ')
print(w1)
r3=r1
c3=1
print('Enter the elements of bias matrix: ')
b1=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    b1[i][j]=input('Enter: ')
print(b1)
r2,c2=map(int,input('Enter then number of rows and columns of batches: ').split())
print('Enter the elements of batch: ')
x1=np.zeros((r2,c2))
for i in range(r2):
  for j in range(c2):
    x1[i][j]=input('Enter: ')
print(x1)
h1=np.dot(w1,x1)+b1
print('result: ')
print(h1)
print('ReLU result: ')
re_val=relu(h1)
print(re_val)
r4,c4=map(int,input('Enter then number of rows and columns of Hidden Layer: ').split())
print('Enter the elements of matrix: ')
w2=np.zeros((r4,c4))
for i in range(r4):
  for j in range(c4):
    w2[i][j]=input('Enter: ')
print(w2)
r5=r4
c5=1
print('Enter the elements of bias matrix: ')
b2=np.zeros((r5,c5))
for i in range(r5):
  for j in range(c5):
    b2[i][j]=input('Enter: ')
print(b2)
h2=np.dot(w2,re_val)+b2
print('result: ')
print(h2)
print('ReLU result: ')
re_val=relu(h2)
print(re_val)

Enter then number of rows and columns of w matrix: 2 2
Enter the elements of matrix: 
Enter: -1
Enter: 1
Enter: 2
Enter: -1
[[-1.  1.]
 [ 2. -1.]]
Enter the elements of bias matrix: 
Enter: 0
Enter: 0
[[0.]
 [0.]]
Enter then number of rows and columns of batches: 2 1
Enter the elements of batch: 
Enter: 2
Enter: 3
[[2.]
 [3.]]
result: 
[[1.]
 [1.]]
ReLU result: 
[[1.]
 [1.]]
Enter then number of rows and columns of Hidden Layer: 2 2
Enter the elements of matrix: 
Enter: 1
Enter: 1
Enter: -1
Enter: 1
[[ 1.  1.]
 [-1.  1.]]
Enter the elements of bias matrix: 
Enter: 0
Enter: 0
[[0.]
 [0.]]
result: 
[[2.]
 [0.]]
ReLU result: 
[[2.]
 [0.]]
