In [14]:

import numpy as np

r3,c3=map(int,input('Enter the size of batch in rows and columns : ').split())
x=np.zeros((r3,c3))
for i in range(r3):
  for j in range(c3):
    x[i][j]=input('Enter: ')
print(x)

n=int(input('Enter the number of w matrix taken: '))
r1,c1=map(int,input('Enter the size of each w matrix in rows and columns : ').split())
r2,c2=map(int,input('Enter the size of each bias matrix in rows and columns : ').split())
for p in range(1,n+1):

  def relu(a):
    return np.maximum(0,a)

  print('Elements of {0} w matrix: '.format(p))
  w=np.zeros((r1,c1))
  for i in range(r1):
    for j in range(c1):
      w[i][j]=input('Enter: ')
  print(w)

  print('Elements of {0} b matrix: '.format(p))
  b=np.zeros((r2,c2))
  for i in range(r2):
    for j in range(c2):
      b[i][j]=input('Enter: ')
  print(b)

  if p==1:
    z=np.dot(w,x)
    y=z+b
    print('Result: ')
    print(y)
    print('ReLU result: ')
    re_val=relu(y)
    print(re_val)
  else:
    z=np.dot(w,re_val)
    y=z+b
    print('Result: ')
    print(y)
    print('ReLU result: ')
    re_val=relu(y)
    print(re_val)






Enter the size of batch in rows and columns : 3 1
Enter: 2
Enter: 0
Enter: 1
[[2.]
 [0.]
 [1.]]
Enter the number of w matrix taken: 4
Enter the size of each w matrix in rows and columns : 3 3
Enter the size of each bias matrix in rows and columns : 3 1
Elements of 1 w matrix: 
Enter: 0
Enter: 1
Enter: 1
Enter: 0
Enter: 0
Enter: 1
Enter: 1
Enter: 1
Enter: 0
[[0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]
Elements of 1 b matrix: 
Enter: 0
Enter: 3
Enter: 0
[[0.]
 [3.]
 [0.]]
Result: 
[[1.]
 [4.]
 [2.]]
ReLU result: 
[[1.]
 [4.]
 [2.]]
Elements of 2 w matrix: 
Enter: 1
Enter: 0
Enter: 1
Enter: 0
Enter: 1
Enter: 0
Enter: -1
Enter: 0
Enter: 1
[[ 1.  0.  1.]
 [ 0.  1.  0.]
 [-1.  0.  1.]]
Elements of 2 b matrix: 
Enter: 0
Enter: -1
Enter: 0
[[ 0.]
 [-1.]
 [ 0.]]
Result: 
[[3.]
 [3.]
 [1.]]
ReLU result: 
[[3.]
 [3.]
 [1.]]
Elements of 3 w matrix: 
Enter: 0
Enter: 0
Enter: 1
Enter: 0
Enter: 1
Enter: 0
Enter: 1
Enter: 0
Enter: 0
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
Elements of 3 b matrix: 
Enter: 0
Enter: